name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Replace with your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test # Replace with your test command

    # You can add deployment commands here if you have a server
