jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub issue with response
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}  # Use the secret here
          script: |
            const { response } = context.payload.client_payload;
            const issueTitle = `Poll Response: ${response}`;
            const issueBody = `Response: ${response} submitted at ${new Date().toLocaleString()}`;
            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
            });
